version: "3.7"
services:
  client:
    build: ./videoclub-frontend
    container_name: client
    restart: always
    networks:
      - frontend
    ports:
      - "9080:80"
    depends_on:
      - server
  server:
    build: ./videoclub-backend
    container_name: server
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - frontend
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  db-data:
    name: db-data
